services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A main worker -l INFO
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery-beat:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A main beat -l info -S django
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
volumes:
  postgres_data:
  redis_data:
